- CMakeLists.txt
- README.md
- catch/CMakeLists.txt
- cmake/leatherman.cmake
- locale/CMakeLists.txt
- locale/inc/leatherman/locale/locale.hpp
- locale/src/posix/locale.cc
- locale/src/windows/locale.cc
- tests/CMakeLists.txt
- tests/main.cc
- vendor/catch/include/catch.hpp
These are a bit lighter-weight than the logging library, so are a
quicker start for getting it all put together.
This can be tested against https://github.com/branan/cfacter/tree/imp/master/CFACT-227-leatherman
> (CFACT-227) Move locale and catch to leatherman

- .travis.yml
- CMakeLists.txt
- cmake/leatherman.cmake
- scripts/cpplint.py
- scripts/travis_target.sh
This doesn't add appveyor yet as I'm not quite sure what's going on with that. This should get travis going, though.
Mostly copied from cfacter
Coverall is currently disabled. #2 has a bunch of changes to `CXXFLAGS` handling, and I'd like to avoid conflicts there. Coveralls can be enabled once everything is in and can be merged cleanly.
> (maint) Add travis configuration

- logging/inc/leatherman/logging/logging.hpp
- logging/src/logging.cc
- logging/tests/logging.cc
Adding the source line number by using the __LINE__ macro.
Updating logging unit tests.
> (LTH-6) Add the source line number to logging messages

- README.md
- json_container/README.md
> (docs) Add README for json_container

- scripts/travis_target.sh
> (docs) Remove reference to cfacter

- scripts/travis_target.sh
> (docs) Fix extra space

- .gitignore
- CMakeLists.txt
- dynamic_library/CMakeLists.txt
- dynamic_library/inc/leatherman/dynamic_library/dynamic_library.hpp
- dynamic_library/src/dynamic_library.cc
- dynamic_library/src/posix/dynamic_library.cc
- dynamic_library/src/windows/dynamic_library.cc
- dynamic_library/tests/dynamic_library_tests.cc
- dynamic_library/tests/fixtures.hpp.in
- dynamic_library/tests/test-lib/goodbye.cc
- dynamic_library/tests/test-lib/hello.cc
- util/inc/leatherman/util/regex.hpp
Extracts facter's dynamic_library classes to Leatherman, including windows and posix variants.
> (LTH-16) Extract facter's dlopen/LoadLibrary wrapper to Leatherman

- CMakeLists.txt
- appveyor.yml
- ruby/CMakeLists.txt
- ruby/inc/leatherman/ruby/api.hpp
- ruby/src/api.cc
- ruby/src/posix/api.cc
- ruby/src/windows/api.cc
- ruby/tests/api-test.cc
Moves facter's Ruby API to Leatherman.
> (LTH-15) Extract facter's Ruby VM hosting to Leatherman

- json_container/inc/leatherman/json_container/json_container.hpp
- json_container/src/json_container.cc
- json_container/tests/json_container_test.cc
This method provides the number of entries of object and array entries
or 0 in case of scalars.
> (LTH-34) Add new JsonContainer::size method

- ruby/inc/leatherman/ruby/api.hpp
- ruby/src/api.cc
- ruby/tests/api-test.cc
Changed some exceptions back to warnings when messages were not facter specific
> (FACT-1136) Move Ruby API to Leatherman

- json_container/inc/leatherman/json_container/json_container.hpp
- json_container/src/json_container.cc
- json_container/tests/json_container_test.cc
New error classes.
Checking the type of the requested entry in get methods (behaviour change).
Improving unit tests.
Style improvements.
> (LTH-33) JsonContainer::get type checks

- json_container/README.md
- json_container/inc/leatherman/json_container/json_container.hpp
- json_container/src/json_container.cc
- json_container/tests/json_container_test.cc
- get methods don't return default values in case of unknown keys; a data_key_error is thrown;
- getting value and type of array elements;
- refactoring the retrieval of elements;
- new toString method for nested elements;
- new unit tests.
> (LTH-37, 35, 32) Processing array elements; improving exception safety

- file_util/inc/leatherman/file_util/directory.hpp
- file_util/src/directory.cc
Porting the following commit from facter/stable:
https://github.com/puppetlabs/facter/commit/436760d3d3dccd26d6057dcd4fb3575de96c7b19
> (maint) Port directory utility function refactoring from Facter stable.

- execution/src/windows/execution.cc
There's a scenario using timeouts where we could release the invoking
end of a named pipe but the other end doesn't release using
Leatherman.Execution. Then the invoking thread shuts down and another
with the same thread id is started and reconnects to the existing named
pipe.
Use the process id and a random number to make that scenario highly
unlikely. This follows a similar pattern used in Chromium:
https://chromium.googlesource.com/chromium/src.git/+/master/base/sync_socket_win.cc#46
> (LTH-51) Protect against potential named pipe re-use

- CHANGELOG.md
- CMakeLists.txt
- README.md
Add entry for pod2man to README
Update changelog.
Bump project version.
> (maint) Prepare for `0.3.6` release

- execution/inc/leatherman/execution/execution.hpp
- execution/src/posix/execution.cc
- execution/src/windows/execution.cc
- locales/leatherman.pot
- ruby/inc/leatherman/ruby/api.hpp
- ruby/src/api.cc
These are needed for FACT-1284, in order to expose the process exit status to the ruby API
> (FACT-1284) Expose pid from execute result; Add rb_last_status_set binding

- README.md
- locales/leatherman.pot
- windows/src/wmi.cc
Ensure we update translations on release.
Fix a comment that's supposed to be with a translation string, and
regenerate translation files.
> (maint) Update translations and release instructions

- README.md
> (maint) Fix formatting on Maintenance

- CHANGELOG.md
- CMakeLists.txt
- locales/leatherman.pot
Make the needed updates for the 0.6.3 release of leatherman.
> (maint) Prepare for 0.6.3 release

- cmake/leatherman.cmake
Previously the symbol_exports helper would set the property and DLL
EXPORT define for all targets in the CMake subtree. This made it
difficult to use when creating test shared libraries. Restrict symbol
exports to only operate on the specific target specified.
> (maint) Isolate symbol exports

- CHANGELOG.md
- CMakeLists.txt
- locales/leatherman.pot
> (packaging) Prepare for 0.7.4 release

- locales/leatherman.pot
- windows/CMakeLists.txt
- windows/inc/leatherman/windows/file_util.hpp
- windows/src/file_util.cc
- windows/tests/file_utils_test.cc
This commit adds a function to get ProgramData using SHGetKnownFolderPath
from Windows API.
> (LTH-106) Add function to get ProgramData

- curl/tests/client_test.cc
- curl/tests/mock_curl.cc
Makes curl_impl an opaque blob using reinterpret_cast to fix compilation
against curl 7.50.0.
> (LTH-108) Fix compilation with curl 7.50.0

- MAINTAINERS
- README.md
Use new maintainers file, and add Maggie and Andy as maintainers.
> (maint) Update maintainers

- .gitignore
- CMakeLists.txt
- README.md
- cmake/leatherman.cmake.in
This commit updates the `gettext_compile` helper to use Leatherman's
install location as a reference point for translation file location.
> (LTH-135) Populate locale file location based on install location

- CHANGELOG.md
- CMakeLists.txt
- locales/leatherman.pot
This updates the versions and the changelog for the 1.0.0 release. Note
that the content is identical to 0.99.0.
> (packaging) Prepare for 1.0.0 release

- README.md
- curl/tests/client_test.cc
- curl/tests/request_test.cc
Remove unnecessary code highlighted by Xcode static analysis.
> (maint) Remove unused code

- .travis.yml
- curl/CMakeLists.txt
- curl/inc/leatherman/curl/client.hpp
- curl/src/client.cc
- curl/tests/client_test.cc
- curl/tests/fixtures.cc
- curl/tests/fixtures.hpp
- curl/tests/mock_curl.cc
- curl/tests/mock_curl.hpp
- locales/leatherman.pot
Leatherman.curl has been extended to now download a file from a
provided URL and write the downloaded contents to a user-specified
file path. Some refactoring was also done in Leatherman.curl to
take out common error-checking patterns.
NOTE: I am going to start writing tests for this PR. This is just to show the main logic and the refactoring.
> (LTH-140) Download file from a given URL

- CHANGELOG.md
- CMakeLists.txt
- locales/leatherman.pot
- util/CMakeLists.txt
- util/inc/leatherman/util/uri.hpp
- util/src/uri.cc
- util/tests/uri.cc
Supports parsing a URI into protocol, host, port, path, and query.
> (LTH-143) Add a uri parsing utility

- .travis.yml
- CHANGELOG.md
- CMakeLists.txt
- locales/leatherman.pot
Uses the cpp-ci container image from Google Container Registry.
> (maint) Update Travis CI to use gcr image

- CMakeLists.txt
- cmake/FindICU.cmake
- locale/CMakeLists.txt
Pulls in the FindICU module from
https://github.com/julp/FindICU.cmake#6fc73154d70b6611027f5475296386c3e66851af
Enabled by setting LEATHERMAN_USE_ICU.
> (maint) Add support for static Boost with ICU

- CONTRIBUTING.md
Since we maintain multiple branches for different releases, add some
useful information for contributors to know when opening pull requests
with their changes.
> (PA-2547) Update CONTRIBUTING.md

- json_container/src/json_container.cc
Signed-off-by: Enis Inan <enis.inan@puppet.com>
> (LTH-169) Pretty print integers as int64_t

- appveyor.yml
The current implementation only checks the exit code of the last command.
With this change appveyour will fail if any command exits with a code != 0
> (maint) PR check fail if tests are failing

- .github/actions/run_cmake_and_make/action.yaml
- CMakeLists.txt
- curl/inc/leatherman/curl/client.hpp
- curl/src/client.cc
- curl/tests/client_test.cc
- curl/tests/mock_curl.cc
- curl/tests/mock_curl.hpp
This reverts commit 36b804bf08336476284b1eb29e9c25285e9b4f2d, reversing changes made to 00ae30e320112aa17ccbc15723f1216b1dbce13f.
> Revert "Merge pull request #340 from mcdonaldseanp/PE36763"
