scripts/travis_target.sh
Coveralls was commented out until CFLAGS setting between
cfacter/leatherman can be cleaned up. Unfortunately bash is terrible.
=> (maint) Fix bash syntax around disabling coveralls

cmake/cflags.cmake
We force use of Unicode on Windows, following the pattern defined at
http://utf8everywhere.org/. Keep the comment from cfacter pointing out
that we're making that choice.
=> (maint) Restore comment about UNICODE on Windows

CMakeLists.txt, cmake/cflags.cmake, cmake/options.cmake
The defoptions that were intended to be shared with containing
projects had been tossed at the top of `cflags.cmake`. It turns out we
really want to think about these as separate things, so they've been
split out.
Also now we only pull in cflags and options if we're top-level. When
leatherman is embedded we want to rely on the calling project to deal
with this stuff.
=> (CFACT-235) Clean up handling of defoptions for use by containing projects

locale/CMakeLists.txt, locale/inc/leatherman/locale/locale.hpp, locale/src/posix/locale.cc, locale/src/windows/locale.cc, logging/CMakeLists.txt, logging/inc/leatherman/logging/logging.hpp, logging/src/logging.cc
Cthun uses stringstream for conversion of port numbers to string,
that's affected by setting locale globally - it introduces comma
separators for 4-digit integers. Separate setting locale for specific
uses out of initializing logging, so it can be incrementally enabled.
=> (CFACT-265) Disable global locale setting

logging/src/logging.cc
On Solaris when using GCC, std::locale is broken.
https://gcc.gnu.org/ml/gcc/2012-08/msg00284.html
Disable using std::locale on Solaris. The defaults support UTF-8.
=> (FACT-914) Avoid std::locale on Solaris with GCC

.travis.yml, logging/CMakeLists.txt
Boost.Log has an implicit dependency on Boost.Chrono. When we statically link,
this gets resolved at compile time and isn't an issue. On most platforms when
we dynamically link, the Boost library location is in LD_LIBRARY_PATH, and
again Boost.Chrono is found.
On Solaris neither of those things are true, which exposed a runtime
dependency on libboost_chrono.so. Resolve this by explicitly depending on the
Chrono library in Leatherman's Logging library.
=> (LTH-5) Add Boost.Chrono explicit dependency

CMakeLists.txt, LeathermanConfig.cmake.in, README.md, catch/CMakeLists.txt, cmake/internal.cmake, cmake/leatherman_config.cmake, locale/CMakeLists.txt, logging/CMakeLists.txt, nowide/CMakeLists.txt
This adds the frameworks necessary to be able to install leatherman, as well as load it with the normal CMake `find_package` facilities. A companion PR to facter demonstrates the usage.
=> (LTH-1) Support 'make install' in leatherman

cmake/leatherman.cmake, logging/CMakeLists.txt, logging/inc/leatherman/logging/logging.hpp, logging/src/logging.cc, logging/tests/logging.cc, logging/tests/logging_lines.cc
Makes logging line numbers a compile-time configuration option that can
be set per-project using the same compiled artifacts of Leatherman. This
is needed to support the `make install` workflow for Leatherman (LTH-1).
=> (LTH-8) Make logging line numbers configurable

appveyor.yml
Future chocolatey versions will require '-y' to install without prompts.
Update the AppVeyor script to use it now before it starts failing.
=> (maint) Update choco calls in AppVeyor

.gitignore, CMakeLists.txt, README.md, util/CMakeLists.txt, util/inc/leatherman/util/scoped_resource.hpp, util/inc/leatherman/util/strings.hpp, windows/CMakeLists.txt, windows/inc/leatherman/windows/process.hpp, windows/inc/leatherman/windows/registry.hpp, windows/inc/leatherman/windows/system_error.hpp, windows/inc/leatherman/windows/user.hpp, windows/inc/leatherman/windows/windows.hpp, windows/inc/leatherman/windows/wmi.hpp, windows/src/process.cc, windows/src/registry.cc, windows/src/system_error.cc, windows/src/user.cc, windows/src/wmi.cc
Move the registry, user, process, system_error, and wmi Windows helper classes from facter to Leatherman, creating a Windows utility library for use in other projects.
=> (LTH-12) Extract facter Windows helpers and wrappers to Leatherman

logging/CMakeLists.txt
The prior LTH-7 commit removed reversing the library link order, but
failed to reverse the order Boost libraries were registered. This lead
to build failures when using static Boost libraries.
Reverse the Boost library order to fix builds with static libraries.
=> (LTH-7) Fix boost static linking order

logging/tests/logging.cc, logging/tests/logging.hpp
Compiling with clang fails, move operator declarations to the boost
namespace because that seems to work.
I'm not really sure why, seems related to https://en.wikipedia.org/wiki/Argument-dependent_name_lookup.
With GCC, somehow the test worked even though padding should've
introduced multiple spaces. Clang showed the error in the test.
Add handling for multiple spaces following the log level string.
=> (maint) Fix compiling logging tests with Clang

appveyor.yml
Updates appveyor to use Boost 1.57, and mirror the Facter config.
=> (maint) Update appveyor to Boost 1.57

.travis.yml, CMakeLists.txt, appveyor.yml, cmake/cflags.cmake
Required for Boost 1.5.7, and adds support for specifying a VERSION on
the project macro.
=> (maint) Bump cmake requirement to 3.2.2

logging/CMakeLists.txt, tests/CMakeLists.txt
Some systems (at least ArchLinux) require pthread to be linked for
Boost.Thread. Add that dependency on Unix systems so other projects will
pick it up.
=> (maint) Add pthread dependency for boost.thread

LeathermanConfig.cmake.in
We switched the vendor workflow to use LEATHERMAN_LIBRARIES but did
not update the script for using an installed leatherman.
=> (maint) export LEATHERMAN_LIBRARIES from LeathermanConfig script

windows/src/wmi.cc
The wmi utility was moved to Leatherman after Facter 3.0 was released,
so some merges from stable to master require merges across-project to
Leatherman. Merge the FACT-1082 fix for COM initialization.
=> (maint) Merge FACT-1082 fix to wmi

.gitignore, file_util/inc/leatherman/file_util/file.hpp, file_util/src/file.cc
The verdict was reached that this method is only useful in Pegasus, so there is no reason to make it generally available.
=> (maint) Moved relative_file_list() and associated structs back to pegasus

.gitignore, file_util/src/directory.cc, util/CMakeLists.txt, util/inc/leatherman/util/regex.hpp, util/inc/leatherman/util/strings.hpp, util/inc/leatherman/util/time.hpp, util/inc/leatherman/util/timer.hpp, util/src/posix/time.cc, util/src/strings.cc, util/src/time.cc, util/src/windows/time.cc
Extracts and standardizes scattered string and time utility functions from cthun-agent, cthun-client, and pegasus.
Currently, there are no unit tests for these methods in any of the original projects. Do we want some for Leatherman?
=> (LTH-18) Extract string and time utility functions to Leatherman

.travis.yml, appveyor.yml, scripts/travis_target.sh
Enable TravisCI container-based builds by avoiding (and explicitly
disabling) sudo and using the APT addon instead.
=> (maint) Use TravisCI container-based builds

logging/src/logging.cc, logging/tests/logging_sink.cc
Extends testing to cover `operator>>` and `get_level`, completing line
coverage of the logging module.
=> (maint) Extend logging tests

.travis.yml
libblkid is not used by Leatherman, so remove it from the TravisCI
config.
=> (maint) Remove unused libraries in Travis config

appveyor.yml, cmake/options.cmake, curl/CMakeLists.txt
Without this change, no option is provided within Leatherman to link
against a static build of libcurl. On Windows, setting CURL_STATICLIB is
required to build against a static build of libcurl to resolve symbols.
Move the CURL_STATIC option and basic configuration from Facter to
Leatherman.
=> (maint) Move CURL_STATIC to Leatherman

scripts/travis_target.sh
Don't fail Travis if uploading to coveralls fails. This is a judgement
call, but coveralls is not essential and may be ignored if the service
is unavailable. If a service goes down, we'd rather it didn't affect the
results of other services.
=> (maint) Ignore coveralls failures

util/inc/leatherman/util/strings.hpp
This is apparently pulled in automatically from other headers on some
compiler versions, but not on my GCC 5.2.0
=> (maint) Add missing <functional> include to strings.hpp

ruby/inc/leatherman/ruby/api.hpp, ruby/src/api.cc
The fact-1123 implementation uses a LoadError to signal when
initialization of libfacter has failed. This ports the necessary
changes from facter.
=> (FACT-1123) Add LoadError to ruby API bindings

curl/src/request.cc, curl/tests/request_test.cc
When providing a body to a POST request, setting the Content-Length
header to the size of the body is required in order for the server to
properly read the body. Currently that's a manual process that always
needs to be done, in the same way, by the user of the curl client for
every request. Since the behavior is always the same and it's always
necessary, the body setter now computes and adds the header
automatically. This can still be overridden by the consumer by setting
the header before adding the body, if they don't want it set (though
it's hard to imagine a reason for that).
=> (maint) Set Content-Length header based on size of the body

logging/CMakeLists.txt
On some Linux and Solaris versions, rt must be explicitly linked as a
dependency for libboost_thread. Add it to dependencies in Logging, the
only library that uses Boost.Thread.
=> (maint) Add rt dependency for Boost.Thread

execution/src/posix/execution.cc
Porting the Facter stable fix to execution that replaced `access` with
an implementation based on `stat` for consistency between platforms.
See FACT-1155 for more information.
=> (LTH-39) Port Facter stable execution fix to Leatherman.

execution/src/windows/execution.cc
Porting the fix for FACT-1128.  This fix updates the Windows execution
library to properly handle running under a job object in Windows.
The execution library will now break away from the current job if it's
possible to do so, rather than failing with a vague "access denied"
error.
=> (maint) Porting Facter stable fix to Leatherman.

appveyor.yml, ruby/CMakeLists.txt
Ruby isn't required to build Leatherman.Ruby, so remove the dependency on it.
Instead let the unit tests fail if Ruby's not present.
=> (LTH-40) Remove build requirement on Ruby

curl/inc/leatherman/curl/client.hpp, curl/src/client.cc, curl/tests/client_test.cc, curl/tests/mock_curl.cc, curl/tests/mock_curl.hpp
This commit adds a wrapper to specify CURLOPT_PROTOCOLS per a curl
request. If no protocol is defined, it will default to all protocols. If
a protocol is defined but one is used that wasn't specified (like using
http when https was the only protocol enabled), it will fail with an
http exception saying that an unsupported protocol was used.
=> (LTH-41) Add function to specify curl protocols

dynamic_library/inc/leatherman/dynamic_library/dynamic_library.hpp, dynamic_library/src/posix/dynamic_library.cc
It's not possible on all platforms to check if a library has been loaded. Instead, the right thing to do is use dynamic_library::find_by_sybmol and only call load if that failed. Since that's the new recommended API usage, and since Facter already does the right thing, load can now unconditionally flag the library as first_load.
=> (FACT-891) Always assume dynamic_library::load is first load

execution/inc/leatherman/execution/execution.hpp, execution/src/execution.cc, execution/src/windows/execution.cc
This ports the fix for FACT-1158 (failure to properly expand commands for Ruby
command execution) that is currently in facter's stable branch to Leatherman.
The fix is to properly quote expanded commands that contain spaces.
Additionally, a new option is added to preserve the arguments so that they
aren't automatically quoted on Windows.
=> (maint) Port fix in facter#stable to Leatherman execution library.

json_container/inc/leatherman/json_container/json_container.hpp, json_container/tests/json_container_test.cc
Before this patch, if users of JsonContainer wanted to try to find
an entry in a JSON object and use a default value if the entry was not
found, they would have to perform a two-step process of checking for the
key and then either getting the key or using the default value. This is
more work than is strictly necessary and leads to superfluous repetition
of this logic. With this patch applied, that logic is centralized in the
`getWithDefault` method, and users can call that function with their
default value instead of implementing the logic themselves.
=> (LTH-43) Add getWithDefault to JsonContainer.

ruby/inc/leatherman/ruby/api.hpp, ruby/src/api.cc
In Facter#stable, the Ruby API was updated to include an uninitialize
method for cleaning up Ruby before DLL unload. Move it to Leatherman.
=> (maint) Merge facter#stable Ruby API changes

logging/src/logging.cc
Just like on Solaris, libstdc++'s locale support is kind of borked on AIX. We shouldn't even bother.
=> (FACT-1230) Don't try to use locale on AIX

execution/inc/leatherman/execution/execution.hpp, execution/src/execution.cc, execution/src/posix/execution.cc, execution/src/windows/execution.cc, execution/tests/posix/execution.cc, execution/tests/windows/execution.cc, ruby/src/api.cc
The execute commands previously had no way to return the exit code from
the child process without throwing an exception. Many use cases include
examining the exit code of a failed child process as normal behavior, so
we should provide a way to get it without using exceptions. Add it to
the return tuple to make it available to callers.
=> (LTH-48) Return exit_code from execute command

logging/src/logging.cc
The log_level error message for unparseable values was
returning the unset log_level rather than the input string.
=> (maint) Fix log level to display input string

cmake/cflags.cmake
Clang in Xcode 7 added a warning we already disabled for GCC, and changed the version string formatting. Fix those things.
=> (maint) Fixes for Xcode 7

execution/inc/leatherman/execution/execution.hpp, execution/src/execution.cc, execution/src/posix/execution.cc, execution/src/windows/execution.cc, execution/tests/fixtures/echo_pid, execution/tests/posix/execution.cc, execution/tests/windows/execution.cc
Adding two overloads for exectution::execute() to redirect stderr and
stdout streams to file (callback based) and execute a callback that
receives the PID of the spawn process.
Adding new unit tests for the new functionality.
=> (LTH-55) Add execute() overloads for PID and stream redirection

json_container/inc/leatherman/json_container/json_container.hpp, json_container/src/json_container.cc
The MemoryPoolAllocator is buggy on Solaris SPARC, and hasn't been shown
to constitute a significant performance benefit for our use. Switch to
using plain CrtAllocator.
=> (LTH-52) Remove use of MemoryPoolAllocator

execution/inc/leatherman/execution/execution.hpp
Here we try to fix a compilation issue with the signature of a variant
of execution::execute where the env map is defined by default to an
empty initiialization list; we replace that with an explicit call to the
default ctor.
=> (maint) Use ctor call instead of empty init list in execute signature

CMakeLists.txt, curl/CMakeLists.txt, dynamic_library/CMakeLists.txt, execution/CMakeLists.txt
The official recommendation from @branan is to install leatherman to the system and build from there, but some testing logic was assuming that leatherman was being used as a vendor library and some cmake files weren't being installed to system locations. This pull request fixes the needful.
=> Bugfixes for using leatherman as a standalone installed library

json_container/inc/leatherman/json_container/json_container.hpp, json_container/src/json_container.cc
Previously, several members of JsonContainer needlessly passed
vectors by value. This commit updates these members to pass by
reference to prevent unnecessary copying, and adds the const
modifier to vector parameters which shouldn't be altered.
In addition, the getWithDefault member has been updated to use
iterators of a vector of keys, rather than altering a copy and
looping over its remaining elements.
=> (LTH-57) Avoid unnecessary vector copying in JsonContainer

ruby/src/api.cc
The move was causing Clang to emit a warning (which we treat as an error due to -Werror). Removing it makes everything better.
=> (maint) Remove redundant move invocation in construction of ruby api instance

appveyor.yml, cmake/cflags.cmake
GCC 5 introduced -deprecated-declarations, which flags Boost's use of
auto_ptr. Disable for now until Boost updates to remove auto_ptr.
Deprecated APIs in Boost.System cause unused variable warnings in GCC
5.2.0. Disable the deprecated APIs.
=> (maint) Fix compilation on Windows with GCC 5.2.0

cmake/leatherman.cmake, scripts/cpplint.py
Updates cpplint to `#409` (cpplint versioning). Resolves linting errors around lambdas;
they require semi-colon after braces but lint thinks that shouldn't happen. Disables a
few new checks that we don't handle consistently.
=> (maint) Update cpplint

CMakeLists.txt
We were omitting the cpplint.py script, which meant that `make cpplint`
would only work with a vendored leatherman install. This commit resolves
this by installing that script during installation.
=> (maint) Install cpplint.py when installing leatherman

appveyor.yml, nowide/CMakeLists.txt
Previously `make install` on Windows didn't work because it would look
for libnowide.dll on the wrong location. Fix the lookup location and
ensure Windows tests `make install`.
=> (maint) Fix install of libnowide.dll

file_util/tests/directory_utils_test.cc, json_container/tests/json_container_test.cc, ruby/tests/api-test.cc
Previous GCC 5.2 work was in the context of building as a submodule. When
building stand-alone we build tests that weren't previously fixed for GCC
5.2 on Windows. Fix them now.
=> (maint) Fix GCC 5.2 issues in tests

nowide/CMakeLists.txt
Most of Leatherman uses static libraries. On Windows, libnowide is an
exception that makes packaging Leatherman awkward. Use static linking
instead to make Leatherman libraries consistent.
This may require minor fixes for using libnowide if consuming projects
weren't previously synchronizing when they flush `boost::nowide::cout`
or `cerr`.
=> (LTH-61) Use static libnowide by default

appveyor.yml, nowide/CMakeLists.txt
Boost.Nowide used really complicated logic to install the library built from a single source file. It also doesn't work when configuring Leatherman to build shared libraries. Build the source file directly instead.
This can't really be verified without https://github.com/puppetlabs/leatherman/pull/109 and disabling tests via `-DLEATHERMAN_ENABLE_TESTING=OFF` (until LTH-63 is fixed).
=> (maint) Simplify nowide compilation

cmake/leatherman.cmake
If the target name is not a valid C-identifier, generate_export_header
will convert it to one. We now do the same thing on Windows when
defining `lib_<target>_EXPORTS`.
=> (maint) Fix symbol_exports for non-identifier targets

.travis.yml, CHANGELOG.md
The previous token was encrypted for puppetlabs/puppet instead of
puppetlabs/leatherman. This one should work for deploys.
=> (maint) Use a github token encrypted for this repo

CHANGELOG.md, windows/CMakeLists.txt
target_link_libraries will cause failures when leatherman projects are
pulled in via find_package.
=> (maint) Use leatherman_deps instead of target_link_libraries in windows

CMakeLists.txt, README.md, cmake/internal.cmake, cmake/leatherman.cmake, cmake/options.cmake
Major RPM distributions define the CMake variable LIB_SUFFIX to determine if libraries should be shipped in /usr/lib64 or /usr/lib. Support the LIB_SUFFIX variable.
Depends on https://github.com/puppetlabs/leatherman/pull/109 for LTH-54.
=> (LTH-64) Support LIB_SUFFIX for multilib install

execution/tests/posix/execution.cc
On OSX with clang/libc++, trying to default-construct a map with an
empty initializer list fails with an error that the constructor is
explicit.
=> (maint) Explicitly construct empty maps in execution tests

dynamic_library/src/windows/dynamic_library.cc, ruby/src/windows/api.cc
When checking whether a Ruby DLL has already been loaded on Windows, we
use a regular expression that also happens to match leatherman_ruby.dll.
Avoid matching it.
A more general solution would be good, but requires more significant
changes.
=> (LTH-71) Avoid matching leatherman_ruby.dll

json_container/README.md, json_container/tests/json_container_test.cc
JsonContainer(std::string s) throws a data_parse_error in case `s` is an
empty string. Here we explicit that in the docs and add a couple of unit
tests.
=> (maint) Document JsonContainer ctor getting empty string

cmake/pod2man.cmake
...because sharing is caring.
This commit adds a pod2man cmake macro to leatherman so that multiple
teams can use the macro for their man pages without copying the code
around!
=> (maint) Add pod2man cmake macro to leatherman

CMakeLists.txt
This commit adds the pod2man macro to the list of install leatherman
macros for downstream consumers.
=> (maint) Install pod2man macro alongside other leatherman macros

CHANGELOG.md, CMakeLists.txt
We're needing to use the pod2man macro in puppet-code, so I think we need a new release with AJ's fix.
=> (maint) Prep for leatherman 0.3.7 release.

README.md
The previous instructions to push a release were incorrect, we need to
push the tag itself.
=> (doc) Fix instructions to push tags for a release

cmake/internal.cmake
Without this change, building Leatherman after it's already been installed
to CMAKE_INSTALL_PREFIX (or if an install happens to exist in
CMAKE_PREFIX_PATH) will pickup the old installed headers before the
Leatherman headers in the project. Fix `include_directories` to add the
project includes first.
=> (maint) Fix project include lookup

locales/leatherman.pot, ruby/inc/leatherman/ruby/api.hpp, ruby/src/api.cc, ruby/tests/api-test.cc
When calling ruby::to_string on a non-UTF-8 encoding, the binary
representation returned will be interpreted incorrectly by the caller.
=> (LTH-84) Fix ruby::to_string when not UTF-8

README.md
This commit adds a bit more context to the readme for using the i18n
features of Leatherman. It adds the work needed to get it compiling in a
projects CMakeLists.txt file, and also gives a small example on the few
lines of code needed for translating and formatting strings.
=> Update example for how to use i18n features

README.md, cmake/leatherman.cmake, cmake/options.cmake, locale/CMakeLists.txt, locales/leatherman.pot, logging/src/logging.cc
Disables localization tests when gettext isn't available.
Also does some minor cleanup.
=> Support projects that don't use gettext

CMakeLists.txt
This commit updates leathermans cmake file to install the
generate_translations.cmake file that is required when generating
translation files.
=> Install generate_translations.cmake file for internationalization

CHANGELOG.md, CMakeLists.txt, locale/CMakeLists.txt, locales/leatherman.pot
Building with static boost libraries on Mac OS X fails because
Boost.Locale requires iconv. Add iconv as a dependency on Mac OS X when
building against static boost.
=> (LTH-87) Fix build on OS X

scripts/travis_target.sh
A prior commit intended to extend `make install` to shared_release and
debug builds, but mistakenly did it for all builds. Skip `make install`
for cpplint and cppcheck builds.
=> (maint) Skip make install for cpplint and cppcheck

execution/inc/leatherman/execution/execution.hpp, execution/src/windows/execution.cc, execution/tests/windows/execution.cc
Adding a new execution_option to the Execution lib to create child
processes in Windows with a new process group and avoid createing
or terminating a related Job Object.
=> (LTH-90) Execution with new process group on Windows

LeathermanConfig.cmake.in, cmake/internal.cmake
When Leatherman is built as a set of shared libraries, all required
dependencies are accounted for in the binary files. However the
LEATHERMAN_LIBS and LEATHERMAN_*_LIBS variables still included dependent
libraries, which could be static libraries. When the dependencies are
static libraries, linking using LEATHERMAN_*_LIBS can result in missing
symbols.
Update Leatherman to leave dependencies out of LEATHERMAN_*_LIBS when
built with shared libraries.
=> (LTH-81) Drop dependencies when using shared libraries

cmake/cflags.cmake
Set C defines to drop support for Windows Server 2003, bringing in new
APIs introduced in Windows Vista.
=> (LTH-89) Drop support for Windows Server 2003

locales/leatherman.pot, ruby/inc/leatherman/ruby/api.hpp, ruby/src/api.cc
Longs have different size on Windows and Linux. Prefer to get long longs,
which are always 64-bits.
=> (LTH-91) Switch to using fixed-size ints

ruby/inc/leatherman/ruby/api.hpp, ruby/src/api.cc, ruby/tests/api-test.cc
A change to using 64-bit integers in the Ruby API assumed size_t would
always be 64-bit. That breaks 32-bit compilation. Restore explicitly
casting to size_t.
Getting a size and expecting it to match size_t is also a common
pattern. Add a helper that does bounds-checking for that cast.
=> (maint) Fix 32-bit compilation

ruby/inc/leatherman/ruby/api.hpp, ruby/src/api.cc, ruby/tests/api-test.cc
Prior to this commit, the Ruby API in leatherman did not have a
method to identify a bignum. Add this method so that we can
identify bignums in addition to fixednums and doubles in facter.
=> (maint) Add is_bignum to Ruby API

cmake/cflags.cmake, curl/tests/CMakeLists.txt, execution/CMakeLists.txt, tests/CMakeLists.txt, windows/src/wmi.cc
CMake adds `-lkernel32` to the list of link libraries by default. However,
doing so with MinGW-w64 introduces an unsatisfied dependency on Nano
Server, causing any executable to fail to run. Explicitly set default link
libraries for all C++ projects to avoid linking kernel32.
Also
- Fix output on WMI error
- Ensure explicit dependencies are first
=> (LTH-93) Support building on Nano Server

ruby/inc/leatherman/ruby/api.hpp
`pid_t` was added to a header without the corresponding include file
`sys/types.h`. On Linux this was fine, but on Mac OS X it causes
compilation errors. Add the include statement.
=> (maint) Fix compilation on Mac OS X using Clang

CHANGELOG.md, CMakeLists.txt, curl/CMakeLists.txt, dynamic_library/CMakeLists.txt, execution/CMakeLists.txt, file_util/CMakeLists.txt, ruby/CMakeLists.txt
On AIX, symbols aren't being resolved from other libraries from dynamic
libraries. In particular, the Boost.Log header files included in
Leatherman.Logging's header uses Boost.Regex, requiring any projects
relying on Leatherman.Logging to link Boost.Regex. Add that dependency.
Leatherman.Execution also had dependencies on Boost.Filesystem that were
being fulfilled from other libraries. Ensure those are called out
explicitly as well, again to resolve runtime failures on AIX.
=> (LTH-94) Add Boost.Regex to all libs using Leatherman.Logging, prepare 0.6.2 release

.travis.yml
cmake.org downloads were very slow (taking several minutes). Switch to
downloading from Puppet's S3 bucket instead.
=> (maint) Download cmake from s3 instead of cmake.org

cmake/options.cmake
Ensures project include files are always preferred over system include
files, avoiding the problem of picking up headers from an installed copy
of Leatherman while building.
=> (maint) Make prefixing project includes the default

logging/tests/logging_on_message.cc
This seems to fail in just about every CI environment, but has been
difficult to reproduce. Skip the test for now.
=> (maint) Disable fragile test

locale/locales/leatherman_test.pot, locale/src/locale.cc, locales/leatherman.pot, logging/inc/leatherman/logging/logging.hpp, logging/src/logging.cc
Previously, if the logging library was built with locale support it
would always be used. This adds a new parameter to the setup_logging
function to allow applications to disable locale support if they
desire.
=> (LTH-97) Allow applications to disable locale support

locales/leatherman.pot, windows/src/wmi.cc
Uses COM multi-threaded (MTA) when single-threaded apartments (STA) aren't
supported. Currently that only occurs on Microsoft Nano Server. This
fixes WMI querios on Nano Server.
Does not change the default to multi-threaded because several providers in
Puppet (user, group, MSI package) use WIN32OLE/COM with STA, and using MTA
in Facter would cause them to fail.
=> (LTH-98) Use COM MTA for Nano Server

.travis.yml, locale/disabled/locale.cc, scripts/travis_target.sh
Code that's only compiled when `LEATHERMAN_USE_LOCALES` is OFF was
incorrect. Fix it and make it more consistent with other code by `using
namespace std`.
Add a Travis run to test this code path.
=> (maint) Fix compilation with LEATHERMAN_USE_LOCALES=OFF

.travis.yml, cmake/leatherman.cmake, cmake/options.cmake, scripts/travis_target.sh
Adds an option to disable using gettext for generating localization
templates and .mo files. This is the simplest way to avoid build issues
until we have new versions of gettext built on all platforms.
=> (maint) Add option to skip gettext

cmake/leatherman.cmake, locale/locales/fr.po, locale/locales/leatherman_locale.pot, locales/leatherman.pot, logging/locales/fr.po, logging/locales/leatherman_logging.pot
Including line numbers in gettext .pot files makes it time-consuming to
merge changes, and adds a lot of noise to commits. Remove them.
Also update Puppet Labs to Puppet.
=> (LTH-103) Remove line number from .pot files

appveyor.yml, scripts/travis_target.sh
Ensures we always attempt to regenerate locales/leatherman.pot, and uses
recent versions of gettext.
=> (LTH-105) Fix gettext in AppVeyor/Travis CI

ruby/src/api.cc
Adds aliasing for a symbol that was renamed in Ruby 2.3 (as a
Ruby API deprecation).
=> (LTH-99) Fix for Ruby 2.3

ruby/src/api.cc
Leatherman must call ruby_cleanup() first to destroy objects managed by the Ruby garbage collector, followed by manual destruction of any remaining objects. Prior to Ruby 2.3, ruby_cleanup() did not initiate garbage collection.
=> (FACT-1454) Fix Leatherman cleanup of Ruby objects

execution/inc/leatherman/execution/execution.hpp, execution/src/posix/execution.cc, execution/src/windows/execution.cc, execution/tests/posix/execution.cc, execution/tests/windows/execution.cc, util/inc/leatherman/util/scoped_env.hpp, util/src/scoped_env.cc, util/tests/scoped_env.cc
The `execute` function was originally implemented for Facter calls to
command-line tools, where it wants consistently parseable output. For
that purpose, it always overrode LC_ALL and LANG.
We now use `execute` for other purposes, so allow inheriting the locale
from the executing process.
=> (LTH-107) Add inherit_locale option to execute

curl/src/client.cc, dynamic_library/src/windows/dynamic_library.cc, execution/src/execution.cc, execution/src/posix/execution.cc, execution/src/windows/execution.cc, file_util/src/file.cc, json_container/CMakeLists.txt, json_container/inc/leatherman/json_container/json_container.hpp, json_container/src/json_container.cc, locales/leatherman.pot, logging/src/logging.cc, ruby/src/api.cc, windows/src/file_util.cc, windows/src/registry.cc, windows/src/system_error.cc, windows/src/wmi.cc
This update marks a variety of exception and error messages for
translation and updates the leatherman.pot file. All logging
messages appear to be properly marked already.
=> (LTH-59) Review and mark translatable strings in Leatherman

locale/inc/leatherman/locale/locale.hpp
The cflags CMake module includes useful settings, but shouldn't be
required to build against Leatherman. Fix compilation so that's true.
=> (LTH-113) Fix building Leatherman without cflags

logging/src/logging.cc
The Logging logger (logging::helper) is currently in charge of checking
the severity (compared to the configured log level) before creating a new
boost.log record. The sink backend (logging::color_writer) does
not check that when it consumes a record (color_writer::consume). Such
behaviour does not cope well with records created by severity loggers
other than the Logging logger, as the severity value gets ignored.
With this commit we deal with the case where a record created with a
third party severity logger has severity equals to 'none'; in such
case, the record will be discarded.
=> (PCP-556) Logging backend doesn't consume records with lvl==none

CHANGELOG.md, CMakeLists.txt, locales/leatherman.pot
The changes to leatherman::execution are needed for [FACT-1356](https://tickets.puppetlabs.com/browse/FACT-1356), which is scheduled to be released as part of Facter 3.5.0 (which in turn will go out in Puppet Agent 1.8.0). So we need to tag a new version of Leatherman.
=> (packaging) Prepare for 0.9.2 release

logging/src/logging.cc
In Boost 1.62, the way sink argument forwarding appears to have changed
in such a way that it failed to identify the implicit creation of a
color_writer. Switch to explicitly creating the color_writer sink.
=> (LTH-115) Fix Boost.Log sink initialization with Boost 1.62

catch/CMakeLists.txt, cmake/internal.cmake, cmake/leatherman.cmake, rapidjson/CMakeLists.txt, tests/CMakeLists.txt
CMake doesn't handle include file dependencies with ExternalProject_Add.
Switch to unpacking files at compile-time so they can be used in
dependency resolution.
=> (LTH-117) Switch to compile-time unpacking vendored packages

cmake/pod2man.cmake
This is a followup on
https://github.com/puppetlabs/orchestrator-client/pull/270
This flag is required when using podman >= 4 or perl 5.24, although I
don't think it has any consequence in leatherman right now since there
are no man pages.
=> (maint) explicitly pass release flag to pod2man

json_container/src/json_container.cc, json_container/tests/json_container_test.cc
Before this patch leatherman could not handle null characters (`\u0000`)
in JSON keys/values because it used the single argument `std::string`
constructor to create `std::string` representations of those keys/values.
The problem was that the null character is treated as the end of the
string by that constructor, so any key/value containing the null character
was truncated at that character when represented as the `std::string`.
The fix is to use the two argument constructor of `std::string` where the
second argument specifies the length of the value to store in the string.
The respective length is readily obtainable from the JSON parsing library.
=> (LTH-116) Handle null characters in JSON strings

cmake/cflags.cmake, execution/CMakeLists.txt, execution/inc/leatherman/execution/execution.hpp, execution/src/posix/execution.cc, execution/src/posix/generic/platform.cc, execution/src/posix/platform.hpp, execution/src/posix/solaris/platform.cc, execution/src/windows/execution.cc, execution/tests/posix/solaris/execution.cc, execution/tests/windows/execution.cc, locales/leatherman.pot
This PR renames the `create_new_process_group` execution option to `create_detached_process`.
The intention of the option was to create a process in such a way it is detached from its parent in terms of their lifespan. On Windows, which was the only platform where the option was implemented, the child process would be killed when the parent process exited in case the option was not specified. On the contrary the child can outlive its parent when the option is specified.
The renaming of the option is a preparation for generalization of the concept to other OSs where it is also applicable (notably Solaris) but where the original name would not make sense or would be misleading.
The other commit in this PR provides the Solaris implementation of the option which mainly entails creating …
=> (LTH-120) Generalized detached process

CHANGELOG.md, CMakeLists.txt, cmake/cflags.cmake, execution/CMakeLists.txt, execution/src/posix/solaris/platform.cc, locales/leatherman.pot
Solaris large file support is needed for the ctrun functionality in
Leatherman.execution. It's tricky to apply everywhere however, which
caused building Facter with this version of Leatherman to fail. Restrict
large file support flags to Leatherman.execution.
Only applying lfs to some files should be safe according to
http://docs.oracle.com/cd/E19455-01/806-0634/6j9vo5alu/index.html
```
Applications may combine objects produced in the large file compilation
environment with objects produced in the transitional compilation
environment, but must be careful with respect to interoperability
between those objects. Applications should not declare global variables
of types whose sizes change between compilation environments.
```
=> (LTH-120) Isolate lfs to Leatherman.execution

execution/CMakeLists.txt, execution/inc/leatherman/execution/execution.hpp, execution/src/posix/execution.cc, execution/src/posix/generic/platform.cc, execution/src/posix/platform.hpp, execution/src/posix/solaris/platform.cc
Traditionally leatherman::execution used `vfork()` for the child process creation because of its higher performance and lower virtual memory requirements. But this turned out to be problematic (deadlock prone) in multi-threaded processes on at least Solaris.
So in this PR a new execution option - `thread_safe` - is introduced, which when specified causes leatherman::execution to use slower but safer `fork()` for the child process creation. If the option is not specified the more performant but more dangerous `vfork()` is used to preserve backward compatibility.
=> (LTH-126) Make it possible to use fork() on demand

CHANGELOG.md, CMakeLists.txt, locales/leatherman.pot, logging/src/logging.cc
On AIX, when used with pxp-agent, logging doesn't work because the
log-level (severity) isn't correctly stored by the severity logger. This
is strange as it does work with Facter; I suspect the cause is due to
differences in linking with a .exe (pxp-agent) vs a .so (libfacter)
against libboost_logging.so. Work around the issue in Boost.Log by using
less of its magic, and instead using an explicit attribute for severity.
=> (LTH-128) Use less Boost.Log magic

CHANGELOG.md, CMakeLists.txt, README.md, locale/CMakeLists.txt, locale/src/locale.cc, locales/leatherman.pot
Allows configuring an environment variable to use at runtime to find
locale files. This environment variable will usually be set by a script
wrapping invocation on Windows.
=> (LTH-133) Allow using an environment variable to lookup locale files

ruby/inc/leatherman/ruby/api.hpp, ruby/src/api.cc
rb_int2inum usually takes a `long`, which can be 32-bits on some
platforms. rb_ll2inum will always give us a 64-bit value, if it's
available.
=> (LTH-134) Add rb_ll2inum binding

ruby/inc/leatherman/ruby/api.hpp, ruby/src/api.cc, ruby/tests/api-test.cc
Ruby 2.4 unified the Fixnum and Bignum types into a single Integer type.
This adjusts Leatherman's Ruby API to take that into account.
NOTE: this will require some updates in Facter, since it is an API breaking change.
=> (LTH-124) Update for Ruby 2.4 unification of Fixnum and Bignum

CHANGELOG.md, CMakeLists.txt, locales/leatherman.pot
This is the first in a series of tags representing pre-release
candidates for Leatherman 1.0.0, which contain backwards-incompatible
API changes.
=> (packaging) prepare for 0.99.0 release

CMakeLists.txt
Enable nxcompat and dynamicbase flags in Windows builds. Being done
to meet some customer's security audit requirements.
=> (LTH-137) Enable DEP support in Windows version of leatherman binaries

execution/src/execution.cc, execution/tests/fixtures/windows/error_message.bat, execution/tests/posix/execution.cc, execution/tests/windows/execution.cc
Previously, iterating over lines without the trim option specified, the
last line could be a single newline. The split iterator takes care of
removing those for all but the last line passed to callbacks. Ensure we
trim line breaks for the last line as well.
=> (LTH-138) Trim trailing newline when using callbacks

cmake/cflags.cmake
Prepends all Leatherman config to CMAKE_CXX_FLAGS, so that the
command-line can override any of the options we specify.
=> (LTH-131) Allow overriding CMAKE_CXX_FLAGS

execution/inc/leatherman/execution/execution.hpp, execution/src/execution.cc, execution/tests/fixtures/error_message, execution/tests/fixtures/windows/error_message.bat, execution/tests/posix/execution.cc, execution/tests/windows/execution.cc
On Windows, the trailing \r\n of buffered output results in the split
including one of the characters. This is inconvenient behavior from
Boost we need to work around. Fix so that any line that is just \r\n is
skipped when using callbacks.
=> (LTH-138) Fix newlines on Windows when redirecting exec

CHANGELOG.md, CMakeLists.txt, curl/inc/leatherman/curl/client.hpp, curl/src/client.cc, curl/tests/client_test.cc, execution/inc/leatherman/execution/execution.hpp, execution/src/execution.cc, execution/tests/posix/execution.cc, execution/tests/windows/execution.cc, file_util/inc/leatherman/file_util/file.hpp, file_util/src/file.cc, file_util/tests/file_utils_test.cc, locales/leatherman.pot
Apply file permissions to stdout and stderr files created for the output
of an executed process.
=> (LTH-139) Allow setting permissions for exec redirection

CHANGELOG.md, CMakeLists.txt, appveyor.yml, locales/leatherman.pot
Updates Appveyor config to use myget-hosted packages. To use them, we
need to use GCC 5.2.0.
=> (maint) Update Windows Appveyor CI to use GCC 5.2.0, use myget

curl/inc/leatherman/curl/client.hpp, execution/inc/leatherman/execution/execution.hpp, file_util/inc/leatherman/file_util/file.hpp
Note that using them is not advised on Windows, as it unexpectedly makes
things read-only. The logic isn't clear at
https://github.com/boostorg/filesystem/blob/boost-1.58.0/src/operations.cpp#L1433-L1453
but I couldn't get a combination of permissions that didn't set
read-only.
=> (maint) Update docs around boost::filesystem::perms

CHANGELOG.md, CMakeLists.txt, curl/inc/leatherman/curl/client.hpp, curl/src/client.cc, curl/tests/client_test.cc, curl/tests/mock_curl.cc, curl/tests/mock_curl.hpp, locales/leatherman.pot
Previously, file operation errors (e.g. setting permissions,
writing to disk) were encapsulated the same way as server-side
errors in a single http_file_download_exception. This commit
creates a new exception for file operation errors,
http_file_operation_exception, to distinguish these cases.
=> (LTH-142) Separate file operation errors from server-side errors

CHANGELOG.md, CMakeLists.txt, curl/inc/leatherman/curl/client.hpp, locales/leatherman.pot
It now inherits from http_request_exception instead of
http_file_download_exception. This makes it explicit in the
exception class which type of error occurred in curl.
=> (maint) Refactor http_file_operation_exception

curl/CMakeLists.txt, curl/inc/leatherman/curl/client.hpp, curl/src/client.cc, curl/tests/client_test.cc, curl/tests/mock_curl.cc, locales/leatherman.pot
Previously, all information about the HTTP response was contained
inside Leatherman.curl's download_file function. Now, the HTTP
response will only be returned for 400+ HTTP statuses.
=> (PCP-785) Return response in download_file if HTTP status > 400

.travis.yml
Travis on Trusty includes Ruby 2.4.1. Fixes for that are in later
branches of Leatherman. Fix by pinning to Precise.
=> (maint) Fix Travis

curl/tests/mock_curl.cc
Xcode 9 produces a new warning: `passing an object that undergoes
default argument promotion to 'va_start' has undefined behavior`.
The signature needs to match libcurl, so we can't change it. Instead
filter the warning.
=> (maint) Filter warning with Xcode 9

execution/src/posix/execution.cc, locales/leatherman.pot
Move towards better exceptions rather than logging errors. This removes
redundancy in logging and allows better debugging in pxp-agent when
sending a PXP error response. May help debug PA-1618.
=> (maint) Make execution exceptions more specific and drop error logging

CHANGELOG.md, CMakeLists.txt, curl/tests/mock_curl.cc, execution/inc/leatherman/execution/execution.hpp, execution/src/posix/execution.cc, locales/leatherman.pot
In testing, we periodically see `failed to run: stdin pipe i/o failed: Broken pipe (32)` on AIX. My hypothesis is that this occurs because the child process exits before we've made a final attempt to write 0 bytes to it and close the pipe. Catch EPIPE when writing 0 bytes and consider the pipe closed.
=> (LTH-149) Handle errors if child has exited before all writing finished

CHANGELOG.md, CMakeLists.txt, locales/leatherman.pot
0.12.2 was tagged without bumping the version number. This is
confusing to our automation, which assumes version files are
authoritative.
Moving forward, leatherman's version file will be managed by this new
automation, so we should not encounter issues like this again.
=> (packaging) Prepare for version 0.12.3 [no-promote]

CMakeLists.txt, locales/leatherman.pot
A new 1.4.x branch has been made from master; This commit preemptively bumps master's reported version to 1.5.0.
=> (packaging) Update reported version to 1.5.0 [no-promote]

curl/inc/leatherman/curl/client.hpp, curl/src/client.cc, curl/tests/client_test.cc, curl/tests/mock_curl.cc, curl/tests/mock_curl.hpp, locales/leatherman.pot
Add ability to configure proxy using CULROPT_PROXY.
https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html
=> (LTH-158) Add proxy support to Curl wrapper

.travis.yml
Accidentally used `-v` previously instead of `-V`.
=> (maint) Use correct flag for verbose test output

cmake/cflags.cmake, dynamic_library/CMakeLists.txt, windows/CMakeLists.txt
These are the changes I needed to make to successfully build leatherman in puppet-agent with boost 1.67 on Windows (the agent PR is here: https://github.com/puppetlabs/puppet-agent/pull/1482)
=> (PA-2055) Prepare for boost 1.67

ruby/inc/leatherman/ruby/api.hpp, ruby/src/api.cc
We had the getter, but not the setter. The setter is needed in order
to implement FACT-1870
=> (maint) Add rb_gv_set to Ruby API bindings

windows/inc/leatherman/windows/wmi.hpp
As documented from https://docs.microsoft.com/en-us/windows/desktop/CIMWin32Prov/win32-computersystemproduct
I've tested this on an agent build with this PR for facter: https://github.com/puppetlabs/facter/pull/1752
Link to ad-hoc build: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/306/
=> (FACT-1872) Add WMI propery for UUID

.travis.yml
The statically-liked boost in Alpine cannot be used to create a shared library as Facter requires. This adds a version which is linked dynamically to allow us to use newer builds of leatherman in Facter.
=> (maint) Add a dynamically-built library tarball to github

cmake/cflags.cmake, cmake/options.cmake
GCC 8.2 outputs far more warnings than previous GCC versions. Thus, to
avoid blocking dev. work on these warnings, this commit adds the
ENABLE_CXX_WERROR option that disables -Werror by default, but still
gives people the option to enable it for e.g. local development.
=> (maint) Add option to enable/disable -Werror

execution/CMakeLists.txt, execution/src/posix/execution.cc
This is a follow-up to #286 by @nwitkowski and @dblacka (I have no permission to push in nwitkowski's repo but have the expected code locally).
I added a commit checking for `closeform(2)` in the CMake configuration and using the new macro instead of checking for the os name.
=> (LTH-160) Use closefrom(2) when available

execution/CMakeLists.txt
`add_compile_defintions` is a relatively new cmake feature; This uses
`add_definitions` in execution's CMakeLists.txt instead for
compatibility with older versions of CMake.
=> (maint) Use add_definitions instead of add_compile_definitions

vendor/nowide/include/boost/nowide/cenv.hpp
cenv.cpp has a line that references a char* without the preceeding *, which
will break builds with newer GCC (TBH I don't know how it worked with older
GCC either?).
This commit simply adds the single *
=> (maint) Add missing pointer reference to string

ruby/inc/leatherman/ruby/api.hpp, ruby/src/api.cc
Ruby >= 2.5 has changed how the Windows sockets are started (see: ruby/ruby@e33b1690), requiring a call to `rb_w32_sysinit` for starting them.
Not having this call causes segmentation faults when querying custom facts that use Windows Sockets with Ruby versions 2.5 and higher.
=> (LTH-163) Call ruby_sysinit to initialize Windows sockets

util/inc/leatherman/util/environment.hpp, util/src/environment.cc, util/tests/environment.cc
Add a new helper function to simplify getting integer environment variables from the system.
The function parameters are the environment variable name, and the default value to return. If the environment variable to get does not exist, or cannot be cleanly coverted to an integer, the default value is returned instead.
Example usage:
```cpp
static const unsigned int EC2_SESSION_TIMEOUT = environment::get_int("EC2_SESSION_TIMEOUT", 5000);
```
=> (FACT-1919) Add environment::get_int to get environment variables as integers

util/src/environment.cc
Environment tests segfault on OS X due to an uncaught exception. Return early from get_int if the variable we're trying to get does not exist.
Fixes an OS X test issue introduced by https://github.com/puppetlabs/leatherman/pull/301.
=> (maint) Fix boost::nowide::getenv on OS X

execution/CMakeLists.txt, execution/src/posix/execution.cc
On systems where `/proc` is available, use `/proc/self/fd` to close only open file descriptors.
Without this change, facter would iterate over the max open file descriptor range and runs would take a long time.
```
$ ulimit -n 1024000
$ ./bin/facter --no-cache
Before: 1024000 - 9s
After:  1024000 - 0,2s
```
Also backports https://github.com/puppetlabs/leatherman/pull/291.
=> (LTH-162) Use /proc where available to close open file descriptors

execution/src/posix/execution.cc
A signal may interrupt a system call such as waitpid, in which case it would return -1 but with errno set to EINTR. The typical solution is to run waitpid inside a while loop and continue looping while waitpid returns -1 with the errno variable is set to EINTR. This patch does exactly that.
This patch fixes this particularly nasty bug: https://tickets.puppetlabs.com/browse/FACT-2019, but one could easily imagine other strange bugs (or rather, Heisenbugs!!!) occurring as a result.
=> (LTH-166) Check if waitpid was merely interrupted

tests/CMakeLists.txt
Currently using boost 1.71 compiling the test executable results in
cmake errors for not using find_package for the required boost
components for proper discovery.
=> cmake: explicit boost components discovery (required for boost 1.71)

windows/inc/leatherman/windows/registry.hpp, windows/src/registry.cc
This commit extends the private `get_regvalue` function to also resolve DWORD values from the registry.
For external usage, the `get_registry_dword` function is added, which behaves similar to `get_registry_string` but works on DWORDs and returns an unsigned long value.
Getting the value as DWORD, converting to wstring, then converting again to unsigned long is redundant but I didn't want to write another function for this specific functionality.
There seem to be no tests for this part of Leatherman.
=> (LTH-168) Get DWORD values from Windows Registry

CMakeLists.txt
1.9.0 was released without running the pipeline, so a manual bump to next version is needed.
=> (packaging) Bump to version '1.10.0' [no-promote]

cmake/cflags.cmake, dynamic_library/CMakeLists.txt, locale/src/locale.cc, util/inc/leatherman/util/strings.hpp, windows/CMakeLists.txt
cherry-pick commits needed to compile with openssl-1.1.1/boost-1.67
=> (PUP-10166) adapt to openssl-1.1.1/boost-1.67

curl/inc/leatherman/curl/client.hpp, curl/src/client.cc, curl/tests/client_test.cc, curl/tests/mock_curl.cc, curl/tests/mock_curl.hpp
This commit allows configuring the `CURLOPT_CRLFILE` https://curl.haxx.se/libcurl/c/CURLOPT_CRLFILE.html curl option in leatherman curl wrapper.
=> (PCP-893) Configure Curl to honor CRL

execution/src/posix/execution.cc
On some systems/kernels, `type builtin` could return `. is a special shell builtin` instead of `. is a shell builtin` which went over our hardcoded buffer size.
Increase the buffer size to also support this case.
=> (LTH-170) Increase builtin check buffer size

util/src/environment.cc
As documented at https://gcc.gnu.org/gcc-10/porting_to.html#cxx the C++ headers in GCC 10 no longer include `<stdexcept>` in places that don't need it. This causes leatherman to fail to compile because it uses `std::invalid_argument` without including the right header.
=> Include header for std::invalid_argument

json_container/src/json_container.cc
Addresses a new warning in Clang 12
```
../json_container/src/json_container.cc:623:26: error: loop variable 'value' is always a copy because the range of type 'std::vector<bool>' does not return a reference [-Werror,-Wrange-loop-analysis]
for (const auto& value : new_value) {
^
```
I also had to set `-Wno-unknown-warning-option` in `CMAKE_CXX_FLAGS` to avoid an unknown warning in the latest version of Boost.
=> (maint) Address warning to build with Clang 12.0.0 on macOS

CMakeLists.txt
OpenSSL in FIPS mode expects `LIBEAY32.dll` to always be loaded at the
same memory address. If the library is relocated for any reason, any
attempts to use it (either as a library or through `openssl.exe`) would
fail and print gibberish on the screen.
As Leatherman is always built with dynamicbase on, there's a small
chance that a Leatherman library gets allocated an address that clashes
with `LIBEAY32.dll` (0x63000000), causing the library to relocate and
fail the FIPS start up check.
By disabling dynamicbase, we ensure that the Leatherman libraries are
always using their base addresses, which are less likely to conflict
with `LIBEAY32.dll`.
This commit adds a DYNAMICBASE CMake option which configures this flag.
Similar work was done for facter in …
=> (PA-3474) Add CMake option to configure dynamicbase

CMakeLists.txt
User error during release meant that these version bumps were never added; manually adding here.
=> (packaging) Bump to version '1.12.10' [no-promote]

.github/workflows/ci_checks.yaml, .github/workflows/release.yaml
The Checkout GitHub Action v3 uses Node 16, which hit end-of-life on September 11, 2023.
This commit updates all instances of the Checkout Action from v3 to v4.
=> (PA-5801) Update Checkout GitHub Action

appveyor.yml
Everything we use leatherman to build with uses -DLEATHERMAN_SHARED=true (linking to it as a shared library), so we don't need to test that cmake flag.
New changes ended up breaking for the mock_curl used for testing with that flag on, and we simply don't have the priority to fix it. So just remove that test
=> (maint) Remove -DLEATHERMAN_SHARED=OFF test

.github/actions/run_cmake_and_make/action.yaml, CMakeLists.txt, curl/inc/leatherman/curl/client.hpp, curl/src/client.cc, curl/tests/client_test.cc, curl/tests/mock_curl.cc, curl/tests/mock_curl.hpp
Update the leatherman curl client to support usage of CURLOPT_PROTOCOLS_STR when it is available. Versions of cURL earlier than 8 will not have CURLOPT_PROTOCOLS_STR, so these changes allow usage of CURLOPT_PROTOCOLS if the new string version of the function is not available.
The _client_protocols param of the client context is now a string, and there is a second implementation of set_supported_protocols that takes a string in the form CURLOPT_PROTOCOLS_STR expects.
Regardless of which version of cURL leatherman is compiled with, both the bitmask and string versions of set_supported_protocols perform the same logic. However the set_client_protocols function - the function that actually calls CURLOPT_PROTOCOLS or CURLOPT_PROTOCOLS_STR - differs: with older cURL it translates the strings …
=> (PE-36763) Add backwards-compat support for CURLOPT_PROTOCOLS_STR
